import type { Metadata } from "next";
import "@/scss/globals.scss";
import { ConditionalLayout } from "@/src/components/layout/ConditionalLayout";
import { TransactionProvider } from "@/src/contexts/TransactionContext";
import { CurrencyProvider } from "@/src/contexts/CurrencyContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></link>
      </head>
      <body className="flex min-h-full bg-white antialiased h-px" style={{ background: "var(--background-gradient)" }}>
        <CurrencyProvider>
          <TransactionProvider>
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
          </TransactionProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}