import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/scss/globals.scss";
import { ConditionalLayout } from "@/src/components/layout/ConditionalLayout";
import { TransactionProvider } from "@/src/contexts/TransactionContext";
import { CurrencyProvider } from "@/src/contexts/CurrencyContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-full bg-white antialiased h-px" style={{ background: "var(--background-gradient)" }}>
        <CurrencyProvider>
          <TransactionProvider>
            <ConditionalLayout>
              {children}
            </ConditionalLayout>
          </TransactionProvider>
        </CurrencyProvider>
      </body>
    </html>
  );
}